<div class="smartcaption taglefttitleright animated">
<% if(paramcaptioncaptiontag != ''){ %>
  <h4>{param text "Caption tag"}</h4>
<% } %>
<% if(paramcaptioncaptiontitle != ''){ %>
<h3>{param text "Caption title"}</h3>
<% } %>
</div>
<script type="text/javascript">
var caption = {
  w: "{param text "Width of the title in px" "200px"}",
  type: "taglefttitleright",
  top: "{param text "Top coordinate of the tag" "0px" "This helps to position the caption on your slide."}",
  interval: {param text "Animation interval" "1000"},
  delay: {param text "Animation delay" "0" "in ms"},
  easing: "{param easing "Animation easing"}"
};
</script>