<div class="onlybackground" style="background-image:url('{param image "Background image url"}');width:{param text "Image width" "100%"};height:{param text "Image height" "100%"};">
<% if(paramcontentlinkforimage != ''){ %>
<a href="{param text "Link for image" "" "If you want to add a link to your image, just fill this field with an url."}" target="{param list "Target window"}_self,Self,_blank,Blank{/param}">
</a>
<% } %>
</div>