<object id="vimeo{param text "Video code" "" "Insert here only the bold text from the url example: http://vimeo.com/19024160"}" width="{param text "Video width" "100%" "Just a number! Usually the canvas width."}" height="{param text "Video height" "100%" "Just a number! Usually the canvas height."}">
  <param name="allowfullscreen" value="true" />
  <param name="allowscriptaccess" value="always" />
  <param name="wmode" value="opaque" />
  <param name="movie" value="http://vimeo.com/moogaloop.swf?clip_id={param text "Video code"}&amp;server=vimeo.com&amp;show_title=0&amp;show_byline=0&amp;show_portrait=0&amp;color=ff9933&amp;fullscreen=1&amp;autoplay=0&amp;loop=0" />
  <embed src="http://vimeo.com/moogaloop.swf?clip_id={param text "Video code"}&amp;server=vimeo.com&amp;show_title=0&amp;show_byline=0&amp;show_portrait=0&amp;color=ff9933&amp;fullscreen=1&amp;autoplay=0&amp;loop=0" type="application/x-shockwave-flash" wmode="opaque" allowfullscreen="true" allowscriptaccess="always" width="{param text "Video width"}" height="{param text "Video height"}">
  </embed>
</object>
<script type="text/javascript">
if(!sliderDojo.hasFlash){
  var node = sliderDojo.byId("vimeo{param text "Video code"}");
  node.parentNode.innerHTML = '<iframe src="http://player.vimeo.com/video/{param text "Video code"}?title=0&amp;color=ff9933" width="{param text "Video width"}" height="{param text "Video height"}" frameborder="0"></iframe>';
}
</script>